### ISSUE TITLE
Time series data

### ISSUE THREAD

**Issue by jcsp** [Tendrl/documentation#25]
Tendrl Core Components mentions that the Central Store handles "Current time series data needed for automated conditional triggers." which I take to mean a specialised subset of the overall time series data.

Where does the rest of the time series data go?

**Comment by brainfunked** [comment]
This has been picked up as https://tendrl.atlassian.net/browse/TEN-49.

**Comment by anmolbabu** [comment]
Please find a brief analysis of some of the time series databases and also some of the findings from skyring 2.0 attached with this comment
[TendrlTimeSeriesDB.pdf](https://github.com/Tendrl/documentation/files/497301/TendrlTimeSeriesDB.pdf)

**Comment by jcsp** [comment]
Things I'm not seeing here:
- Consideration of performance limits (graphite starts to perform badly beyond a certain number of metrics because it's storing everything in a file per metric, generating huge amounts of random disk IO.  You need to find that limit and see if it is acceptable for the scope of what you want to store in Tendrl).
- Consideration of high availability (this varies a lot between different systems)
- Consideration of security and network protocols (how is times series data getting from storage nodes to the time series database?)

It seems like the argument for graphite boils down to the single bullet point "influxdb was not very mature" -- otherwise influxdb would be clearly superior, right?

**Comment by anmolbabu** [comment]
Outcomes and/or excerpts of my conversation with jcsp:
1. graphite starts to perform badly beyond a certain number of metrics because it's storing  everything in a file per metric, generating huge amounts of random disk IO..
For skyring 2.0, the metrics chosen for monitoring were : 
    Physical resources: 
          cpu, memory, network throughput, disk iops, swap, network, network latency, mount points utilizations
    Ceph specific:
          Cluster Utilization, Pool Utilization, Osd utilization, rbd utilization, pg summary and object count
Ceph provides a huge set of performance data. We need to decide on whether we stick to the above list or there will be more  added to the list. Calamari uses graphite and if graphite were to handle all the performance data which ceph provides, graphite will not be able to stand up to that kind of load
2. Graphite uses plain text over a tcp socket, no encryption, no authentication, lots of people running their own networks don't necessarily care, but it becomes a deployment constraint that we would require the network to be completely secure and isolated.
3. In-depth evaluation of prometheus and/or influxdb might be good as they don't have the same basic performance problem that the graphite does.
