### ISSUE TITLE
Document the shrink cluster workflow in tendrl

### ISSUE THREAD

**Issue by shtripat** [Tendrl/documentation#35]
This is something which might be required if cluster storage is under-used and admin wants to take out few devices and use them for different purpose. Its critical to have clear flow defined and implemented as it needs data movement to the left out devices and there should not be any data loss during this process. Also the inventory structure gets changed maintained with tendrl.

**Comment by sankarshanmukhopadhyay** [comment]
@shtripat is this something which is already referenced in @julienlim's document? If yes, could you cite it?

On the face of it, the issue seems to be something which would need to be addressed when the task is being handled during a sprint. If there are additional considerations ie. things to be aware of when designing the flow, please document it here.

**Comment by shtripat** [comment]
@sankarshanmukhopadhyay the shrink cluster feature was not available in skyring and it might not be in UX document as well. I keep the issue, so that we dont lose the importance of this feature. We might keep it open till we work on this.

**Comment by cybernth** [comment]
This is something which we need support from sds provisioning systems(in case of ceph ceph-installer and ceph-ansible should support this). replace node use case also has a dependency on this.
